# Generated by Django 4.2.1 on 2023-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='porcentagem',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
